#!/usr/bin/env bash

# Source: https://github.com/mhanberg/.dotfiles/blob/main/bin/git-branches-sorted

git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))' --color=always
