#!/usr/bin/env bash

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 R G B"
else
  echo -en "\e[48;2;$1;$2;$3m TEST \e[0m"
  echo -n ":  "
  echo "\e[48;2;$1;$2;$3m TEST \e[0m"
  echo -en "\e[38;2;$1;$2;$3m TEST \e[0m"
  echo -n ":  "
  echo "\e[38;2;$1;$2;$3m TEST \e[0m"
fi
