#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys

if os.name == "posix":
    downloads_folder = os.path.join(os.path.expanduser("~"), "Downloads")
else:
    sys.exit("Operating system not supported")


def move_file_to(file, destination):
    src = os.path.join(downloads_folder, file)
    dst = os.path.join(downloads_folder, destination, file)
    if os.path.isfile(src):
        os.rename(src, dst)


for file in os.listdir(downloads_folder):
    if file.lower().endswith(
        (".png", ".jpg", ".jpeg", ".gif", ".tif", ".tiff", ".bpm", ".svg")
    ):
        move_file_to(file, "Pictures")
    elif file.lower().endswith((".mp3", ".wav", ".mpa")):
        move_file_to(file, "Music")
    elif file.lower().endswith((".mp4", ".avi", ".mov", ".wmv", ".flv")):
        move_file_to(file, "Videos")
    elif file.lower().endswith(
        (".pdf", ".xls", ".xlsx", ".doc", ".docx", ".ppt", ".pptx")
    ):
        move_file_to(file, "Documents")
    elif file.lower().endswith((".fnt", ".fon", ".otf", ".ttf")):
        move_file_to(file, "Fonts")
    elif file.lower().endswith((".csv", ".dat", ".xml", ".vcf")):
        move_file_to(file, "Data")
    elif file.lower().endswith((".zip", ".tar", ".rar", ".7z")):
        move_file_to(file, "Compressed")
    else:
        move_file_to(file, "Misc")
