#!/bin/sh

if command -v xclip &> /dev/null; then
    if [ -f $@ ]; then
        cat $@ | xclip -selection clipboard
    else
        echo $@ | xclip -selection clipboard
    fi
else
    if [ -f $@ ]; then
        cat $@ | xsel -ib
    else
        echo $@ | xsel -ib
    fi
fi

# vim: ft=shell
