#!/usr/bin/env bash

# ls /usr/share/cowsay/cows
PICTURES=(
    apt
    beavis.zen
    bong
    bud-frogs
    bunny
    calvin
    cheese
    cock
    cower
    daemon
    dragon
    dragon-and-cow
    duck
    elephant
    elephant-in-snake
    eyes
    flaming-sheep
    ghostbusters
    gnu
    hellokitty
    kiss
    kitty
    koala
    kosh
    luke-koala
    mech-and-cow
    meow
    milk
    moofasa
    moose
    pony
    pony-smaller
    ren
    sheep
    skeleton
    snowman
    stegosaurus
    stimpy
    suse
    three-eyes
    turkey
    turtle
    tux
    unipony
    unipony-smaller
    vader-koala
    www
)

rand=$((RANDOM % 47))

cowsay -f "${PICTURES[rand]}" "$1" | lolcat
