#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys

courses = sys.argv[1:]

subfolders = [
    "Apontamentos",
    "Bibliografia",
    "Exercícios",
    "Formulários",
    "Slides",
    "Testes",
    "Projetos",
]

for course in courses:
    for subfolder in subfolders:
        os.makedirs(os.path.join(course, subfolder))
