#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys

courses = sys.argv[1:]
home_path = os.path.expanduser("~")
documents_folder = os.path.join(home_path, "Documents")

subfolders = [
    "Apontamentos",
    "Bibliografia",
    "Exercícios",
    "Formulários",
    "Slides",
    "Testes",
    "Projetos",
]

os.chdir(documents_folder)

for course in courses:
    for subfolder in subfolders:
        os.makedirs(os.path.join(course, subfolder))
