#!/usr/bin/env bash

cd "$(dirname "$0")" || exit 1

nix-shell -p xorg.libxshmfence --run \
'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(nix eval --raw nixpkgs#xorg.libxshmfence)/lib appimage-run ./eDEX-UI-Linux-x86_64.AppImage'
