#!/usr/bin/env bash

function shortner() {
  URL="$1"
  curl -sS -H "Content-Type: application/json" \
    -X POST https://estev-ao.herokuapp.com/links -d "{
        \"url\": \"$URL\"
    }"
}

shortner "$1" | jq .link | sed 's/"//g' | copy
