#!/bin/bash

if [ ! -d .git ]; then
    echo "Must cd to git top-level directory"
    exit 1
fi

branch=$( git branch | sed -n -e 's/^\* \(.*\)/\1/p' )
if [ -z "$branch" ]; then
    echo "No git branch found"
    exit 1
fi

origin=$( perl -lne'print "$1" and exit if /github.com[:\/](\w+\/\w+)/' \
          < .git/config )

xdg-open "https://github.com/$origin/tree/$branch" & disown

