#!/usr/bin/env bash

SSH_PUB=$HOME/.ssh/id_rsa.pub

display_help() {
  cat <<EOF
USAGE:
        keygen [OPTIONS] [COMMENT]

EXAMPLE:
        keygen email@example.com

OPTIONS:
        -h, --help          Display this help message.
EOF
}

generate_new_key() {
  local COMMENT=${1:-$(whoami)@$(uname -n)}
  ssh-keygen -t rsa -b 4096 -C "$COMMENT"

  if command -v xclip >/dev/null 2>&1; then
    xclip -selection clipboard <"$SSH_PUB"
  else
    echo "[ssh]: xclip not found, you need to copy manually the following key"
    cat "$SSH_PUB"
    exit 1
  fi

  echo "[ssh]: SSH public key copied into the clipboard"
}

case $1 in
  -h | --help)
    display_help
    ;;
  *)
    generate_new_key "$1"
    ;;
esac
