#!/usr/bin/env bash

set -Eeuo pipefail

BASE_DIR=$(dirname "${BASH_SOURCE[0]:-$0}")
cd "${BASE_DIR}/.." || exit 127

# shellcheck source=./helpers.sh
. helpers.sh

PROGRAM=$(basename "${BASH_SOURCE[0]:-$0}")
VERSION=0.4.0

function display_help() {
  cat <<EOF
  $(help_section Usage)
    ${PROGRAM} [options] (<theme> | <screen>)

  $(help_section Themes)
    dark
    light

  $(help_section Screens)
    // work            2 screens stacked (eDP1 on bottom)
    work            2 screens side-by-side (eDP1 on right)
    home            2 screens side-by-side
    pitch           2 screens 2nd on top
    chill           1 screen (eDP1)
    focus           1 screen (HDMI1)
    demo            ~2 screens mirror~, notifications off and increase font-size

  $(help_section Options)
    -h, --help      Show this screen.
    -v, --version   Show version.
EOF
}

function i3restart() {
  i3-msg restart >/dev/null
  numlockx on
  setcapslock off
  setxkbmap -option ctrl:nocaps
}

function toggle_keyboard_backlight() {
  declare -r brightness=$(cat /sys/class/leds/tpacpi::kbd_backlight/brightness)

  if [[ $brightness -eq 0 ]]; then
    echo 1 >/sys/class/leds/tpacpi::kbd_backlight/brightness
  else
    echo 0 >/sys/class/leds/tpacpi::kbd_backlight/brightness
  fi
}

function get_caffeine_status() {
  schemasdir=$(nix eval --raw nixpkgs#gnomeExtensions.caffeine)/share/gnome-shell/extensions/caffeine@patapon.info/schemas

  gsettings --schemadir "$schemasdir" get org.gnome.shell.extensions.caffeine cli-toggle
}

function set_caffeine() {
  declare -r status="$1"
  # TODO: upgrade gnomeExtensions.caffeine to v59
  return

  # gnome-extensions disable caffeine@patapon.info
  # gnome-extensions enable caffeine@patapon.info
  schemasdir=$(nix eval --raw nixpkgs#gnomeExtensions.caffeine)/share/gnome-shell/extensions/caffeine@patapon.info/schemas

  case $status in
    on)
      gsettings --schemadir "$schemasdir" set org.gnome.shell.extensions.caffeine cli-toggle true
      ;;
    off)
      gsettings --schemadir "$schemasdir" set org.gnome.shell.extensions.caffeine cli-toggle false
      ;;
  esac
}

function set_notifications() {
  declare -r status="$1"

  case $status in
    on)
      # dunstctl set-paused true
      gsettings set org.gnome.desktop.notifications show-banners true
      ;;
    off)
      # dunstctl set-paused false
      gsettings set org.gnome.desktop.notifications show-banners false
      ;;
  esac
}

function set_editor_font_size() {
  declare -r code_settings="$DOTFILES/home/programs/vscode/settings.json"
  declare -r size="$1"

  sed -i -e "s/\"editor.fontSize\": .*/\"editor.fontSize\": ${size},/g" "${code_settings}"
}

function set_terminal_background_opacity() {
  declare -r opacity="$1"
  declare -r ghostty_config="$DOTFILES/home/programs/ghostty/config"

  sed -i "s/background-opacity =.*/background-opacity = ${opacity}/g" "${ghostty_config}"
}

function set_terminal_font_size() {
  # declare -r wezterm_config="$DOTFILES/home/programs/wezterm/wezterm.lua"
  declare -r size="$1"
  declare -r ghostty_config="$DOTFILES/home/programs/ghostty/config"
  declare -r code_settings="$DOTFILES/home/programs/vscode/settings.json"

  # sed -i "s/config.font_size =.*/config.font_size = ${size}/g" "${wezterm_config}"
  sed -i "s/font-size =.*/font-size = ${size}/g" "${ghostty_config}"

  sed -i -e "s/\"terminal.integrated.fontSize\": .*/\"terminal.integrated.fontSize\": ${size},/g" "${code_settings}"
}

function get_theme() {
  # declare -r config_file="$DOTFILES/alacritty/alacritty.toml"
  #
  # grep 'import = *' $config_file | awk -F '.' '{ print $3 }'
  # gsettings get org.gnome.desktop.interface color-scheme | grep -oE 'dark|light'
  case "$(gsettings get org.gnome.desktop.interface color-scheme)" in
    *'dark'*) echo "dark" ;;
    *'light'*) echo "light" ;;
    *) echo "light" ;;  # Default to light if neither is found
  esac
}

function change_screen_to() {
  case $1 in
    work)
      autorandr work
      ;;
    home)
      autorandr home
      ;;
    chill)
      theme dark
      set_caffeine off
      set_notifications on
      set_terminal_background_opacity 0.5
      set_editor_font_size 18
      set_terminal_font_size 16
      ;;

    pitch) ;;

    focus) ;;

    demo)
      theme light
      set_caffeine on
      set_notifications off
      set_terminal_background_opacity 1
      set_editor_font_size 32
      set_terminal_font_size 26
      ;;
  esac

  # nitrogen --restore 2>/dev/null
  # i3restart
  echo "Changed to mode $1!"
}

case ${1:-error} in
  -h | --help)
    display_help
    ;;
  -v | --version)
    display_version "$PROGRAM" "$VERSION"
    ;;
  -t | --theme)
    get_theme
    ;;
  -k | --keyboard)
    toggle_keyboard_backlight
    ;;
  dark | light)
    change_theme_to "$1"
    ;;
  work | home | chill | pitch | focus | demo)
    change_screen_to "$1"
    ;;
  *)
    display_help >&2
    exit 1
    ;;
esac
