#!/usr/bin/env bash

set -Eeuo pipefail

BASE_DIR=$(dirname "${BASH_SOURCE[0]:-$0}")
cd "${BASE_DIR}/.." || exit 127

# shellcheck source=./helpers.sh
. helpers.sh

PROGRAM=$(basename "${BASH_SOURCE[0]:-$0}")
VERSION=0.4.0

function display_help() {
  cat <<EOF
  $(help_section Usage)
    ${PROGRAM} [options] (<theme> | <screen>)

  $(help_section Themes)
    dark
    light
    default

  $(help_section Screens)
    work            2 screens side-by-side
    pitch           2 screens 2nd on top
    chill           1 screen (eDP1)
    focus           1 screen (HDMI1)
    demo            2 screens mirror and notifications off

  $(help_section Options)
    -h, --help      Show this screen.
    -v, --version   Show version.

  $(help_section Notes)
    $(italic "Activate the notifications with 'dunstctl set-pause false'!")
EOF
}

function change_theme_to() {
  declare -A themes=(
    ["dark"]="google-dark"
    ["light"]="google-light"
    ["default"]="brewer"
  )

  declare -r theme=${themes[$1]}

  color -s "$theme"

  echo "Theme changed to $theme!"
}

function change_screen_to() {
  local external_monitor
  external_monitor=$(xrandr -q | grep " connected" | tail -n -1 | cut -d" " -f1)
  case $1 in
    work)
      xrandr --output "$external_monitor" --primary --auto --right-of eDP1 --output eDP1 --auto --mode 1600x900
      ;;
    chill)
      xrandr --output eDP1 --primary --mode 1920x1080 --auto --output "$external_monitor" --off
      ;;
    pitch)
      xrandr --output "$external_monitor" --auto --above eDP1 --output eDP1 --primary --auto
      ;;
    focus)
      xrandr --output "$external_monitor" --primary --auto --output eDP1 --off
      ;;
    demo)
      xrandr --output "$external_monitor" --auto --same-as eDP1 --output eDP1 --primary --auto
      dunstctl set-paused true
      ;;
  esac

  i3-msg restart
  echo "Changed to mode $1!"
}

case ${1:-error} in
  -h | --help)
    display_help
    ;;
  -v | --version)
    display_version "$PROGRAM" "$VERSION"
    ;;
  dark | light | default)
    change_theme_to "$1"
    ;;
  work | chill | pitch | focus | demo)
    change_screen_to "$1"
    ;;
  *)
    display_help >&2
    exit 1
    ;;
esac
