#!/usr/bin/env bash

set -Eeuo pipefail

BASE_DIR=$(dirname "${BASH_SOURCE[0]:-$0}")
cd "${BASE_DIR}/.." || exit 127

# shellcheck source=./helpers.sh
. helpers.sh

PROGRAM=$(basename "${BASH_SOURCE[0]:-$0}")
VERSION=0.4.0

function display_help() {
  cat <<EOF
  $(help_section Usage)
    ${PROGRAM} [options] (<theme> | <screen>)

  $(help_section Themes)
    dark
    light

  $(help_section Screens)
    chill           Notifications on, caffeine off, default font-size and dark mode
    demo            Notifications off, caffeine on, big font-size and light mode

  $(help_section Options)
    -h, --help      Show this screen.
    -v, --version   Show version.
    -t, --theme     Show current theme.
EOF
}

function set_notifications() {
  declare -r status="$1"

  case $status in
    on)
      # dunstctl set-paused true
      gsettings set org.gnome.desktop.notifications show-banners true
      ;;
    off)
      # dunstctl set-paused false
      gsettings set org.gnome.desktop.notifications show-banners false
      ;;
  esac
}

function set_editor_font_size() {
  declare -r code_settings="$DOTFILES/home/programs/vscode/settings.json"
  declare -r size="$1"

  sed -i -e "s/\"editor.fontSize\": .*/\"editor.fontSize\": ${size},/g" "${code_settings}"
}

function set_terminal_background_opacity() {
  declare -r opacity="$1"
  declare -r ghostty_config="$DOTFILES/home/programs/ghostty/config"

  sed -i "s/background-opacity =.*/background-opacity = ${opacity}/g" "${ghostty_config}"
}

function set_terminal_font_size() {
  # declare -r wezterm_config="$DOTFILES/home/programs/wezterm/wezterm.lua"
  declare -r size="$1"
  declare -r ghostty_config="$DOTFILES/home/programs/ghostty/config"
  declare -r code_settings="$DOTFILES/home/programs/vscode/settings.json"

  # sed -i "s/config.font_size =.*/config.font_size = ${size}/g" "${wezterm_config}"
  sed -i "s/font-size =.*/font-size = ${size}/g" "${ghostty_config}"

  sed -i -e "s/\"terminal.integrated.fontSize\": .*/\"terminal.integrated.fontSize\": ${size},/g" "${code_settings}"
}

function get_theme() {
  theme status
}

function set_theme() {
  theme "$1"
}

function get_caffeine() {
  caffeine status
}

function set_caffeine() {
  caffeine "$1"
}

function change_to() {
  case $1 in
    chill)
      set_theme dark
      set_caffeine off
      set_notifications on
      set_terminal_background_opacity 0.5
      set_editor_font_size 18
      set_terminal_font_size 16
      ;;

    pitch) ;;

    demo)
      set_theme light
      set_caffeine on
      set_notifications off
      set_terminal_background_opacity 1
      set_editor_font_size 32
      set_terminal_font_size 26
      ;;
  esac

  echo "Changed to mode $1!"
}

case ${1:-error} in
  -h | --help)
    display_help
    ;;
  -v | --version)
    display_version "$PROGRAM" "$VERSION"
    ;;
  -t | --theme)
    theme status
    ;;
  -k | --keyboard)
    ;;
  dark | light)
    theme "$1"
    ;;
  chill | pitch | demo)
    change_to "$1"
    ;;
  *)
    display_help >&2
    exit 1
    ;;
esac
