#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, re

aliases_file_name = "/tmp/aliases.tmp"
history_file_name = os.path.expanduser("~") + "/.zsh_history"

os.system(f'zsh -c "source ~/.zshrc; alias > {aliases_file_name}"')

aliases = {}
aliases_file = open(aliases_file_name)
for line in aliases_file:
    alias, command = line.strip().split("=", 1)
    aliases[alias] = re.sub("'", "", command.split()[0])

statistics = {}
history_file = open(history_file_name)
for line in history_file:
    trash, command = line.strip().split(";", 1)
    command = command.split()[0]
    if command in aliases:
        if aliases[command] in statistics:
            statistics[aliases[command]] += 1
        else:
            statistics[aliases[command]] = 1
    else:
        if command in statistics:
            statistics[command] += 1
        else:
            statistics[command] = 1

total = 0
for v in statistics.values():
    total += v

results = sorted(statistics.items(), key=lambda x: x[1], reverse=True)

n = 1
for result in results:
    k, v = result
    print("{:2}   {:5.2f}% {:5}   {}".format(n, v / total * 100, v, k))
    if n == 10:
        break
    n = n + 1
