#!/bin/sh

copy_file() {
  # only works with text and PNG ¯\_(ツ)_/¯
  FILE=$1
  EXTENSION=${FILE#*.}

  if
    file $FILE | grep -qE 'image' &
    >/dev/null
  then
    xclip -selection clipboard -t image/"$EXTENSION" -i "$FILE"
  else
    xclip -selection clipboard -i "$@"
  fi
}

if
  command -v xclip &
  >/dev/null
then
  if [ -f "$1" ]; then
    copy_file "$1"
  else
    echo "$1" | xclip -selection clipboard
  fi
else
  if [ -f "$1" ]; then
    cat "$1" | xsel -ib
  else
    echo "$1" | xsel -ib
  fi
fi

#vim: ft=sh
